Set up CLI shell API session if not already open

diff --git a/vyatta-quicktun/opt/vyatta/sbin/vyatta-restart-quicktun b/vyatta-quicktun/opt/vyatta/sbin/vyatta-restart-quicktun
--- a/vyatta-quicktun/opt/vyatta/sbin/vyatta-restart-quicktun
+++ b/vyatta-quicktun/opt/vyatta/sbin/vyatta-restart-quicktun
@@ -2,8 +2,15 @@
 
 cli-shell-api inSession
 if [ $? -ne 0 ]; then
-    echo "Unable to set up API session to read back config"
-    exit -1
+    session_env=$($SHELL_API getSessionEnv $PPID)
+    eval $session_env
+    cli-shell-api setupSession
+    cli-shell-api inSession
+
+    if [ $? -ne 0 ]; then
+        echo "Unable to set up API session to read back config"
+        exit -1
+    fi
 fi
 
 if [ -n $1 ];
